language: groovy
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

script:
  - ./gradlew check

after_success:
  - ./gradlew jacocoTestReport coveralls || ./gradlew clean

after_failure:
  - ./gradlew clean check --debug

notifications:
  irc: "irc.freenode.org#anchos"
